### PR TITLE
Documentation Upgrades

### PR DESCRIPTION
**Pull request by ndungudedan**

### CODE REVIEW

**Comment by asoltys** [comment]
Looking good! Let me know when you're ready for me to merge

**Comment by ndungudedan** [comment]
Hi Adam.
For some reason I can't figure out why the mints don't start up after a fresh clone. Here's the error I see on the logs:

`Poetry could not find a pyproject.toml file in /app or its parents`

**Comment by ndungudedan** [comment]
@asoltys This PR is now good for a merge.

**Comment by asoltys** [comment]
Thank you!

**Pull request merged**
